## Task 4

### Question on Numpy-

#### 1) Import the numpy package under the name np and Print the numpy version and the configuration 

In [1]:
import numpy as np

print(np.__version__)
print(np.show_config())

1.22.3
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SU

#### 2) Create a null vector of size 10

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3) Create Simple 1-D array and check type and check data types in array

In [3]:
arr1 = np.arange(0, 7)
arr1

array([0, 1, 2, 3, 4, 5, 6])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.dtype

dtype('int32')

#### 4) How to find number of dimensions, bytes per element and bytes of memory used?

In [6]:
print(f"No of Dimension of the array : {arr1.ndim}")
print(f"Size of the element in the array : {arr1.itemsize}")
print(f"Total Size of the array : {arr1.nbytes}")

No of Dimension of the array : 1
Size of the element in the array : 4
Total Size of the array : 28


#### 5) Create a null vector of size 10 but the fifth value which is 1

In [7]:
null_arr = np.zeros(10)
null_arr[4] = 1
print(null_arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6) Create a vector with values ranging from 10 to 49

In [8]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7) Reverse a vector (first element becomes last)

In [9]:
print(f"Before Reversing : {arr1}")
print(f"After Reversing : {arr1[::-1]}")

Before Reversing : [0 1 2 3 4 5 6]
After Reversing : [6 5 4 3 2 1 0]


#### 8) Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
matrix = np.arange(0, 9).reshape((3, 3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9) Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
arr1 = [1, 2, 0, 0, 4, 0]
arr1

[1, 2, 0, 0, 4, 0]

In [12]:
np.nonzero(arr1)

(array([0, 1, 4], dtype=int64),)

#### 10) Create a 3x3 identity matrix

In [13]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11) Create a 3x3x3 array with random values

In [15]:
np.random.random((3, 3, 3))

array([[[0.67012519, 0.63696252, 0.64382064],
        [0.87186324, 0.32800793, 0.8493937 ],
        [0.67781969, 0.48434286, 0.86905244]],

       [[0.81152778, 0.14333031, 0.97044849],
        [0.16678144, 0.20449546, 0.87621067],
        [0.91985981, 0.50956025, 0.91787687]],

       [[0.80475098, 0.38479581, 0.39343735],
        [0.24412678, 0.4576933 , 0.85234064],
        [0.94662241, 0.76984936, 0.20946275]]])

#### 12) Create a 10x10 array with random values and find the minimum and maximum values

In [16]:
arr1 = np.random.random((3, 3, 3))
print(f"Original Array :\n {arr1}")
print(f"\nMinimum value in the array : {np.min(arr1)}")
print(f"Maximum value in the array : {np.max(arr1)}")

Original Array :
 [[[0.394115   0.86819998 0.55673113]
  [0.28219446 0.61968706 0.67227178]
  [0.45263554 0.04047115 0.14310621]]

 [[0.19947071 0.27979007 0.74257107]
  [0.82896852 0.81537827 0.0777871 ]
  [0.87199545 0.00324801 0.85742635]]

 [[0.26455635 0.59351003 0.05171798]
  [0.91750995 0.97207757 0.33910415]
  [0.70009294 0.93749011 0.87365951]]]

Minimum value in the array : 0.003248012604922912
Maximum value in the array : 0.9720775686926265


#### 13) Create a random vector of size 30 and find the mean value

In [17]:
print(f"Original Array :\n {arr1}")
print(f"\nMean value of the array : {np.mean(arr1)}")

Original Array :
 [[[0.394115   0.86819998 0.55673113]
  [0.28219446 0.61968706 0.67227178]
  [0.45263554 0.04047115 0.14310621]]

 [[0.19947071 0.27979007 0.74257107]
  [0.82896852 0.81537827 0.0777871 ]
  [0.87199545 0.00324801 0.85742635]]

 [[0.26455635 0.59351003 0.05171798]
  [0.91750995 0.97207757 0.33910415]
  [0.70009294 0.93749011 0.87365951]]]

Mean value of the array : 0.5316950530983033


#### 14) Create a 2d array with 1 on the border and 0 inside

In [18]:
arr1 = np.ones((5, 5))
arr1[1:4, 1:4] = 0
arr1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 15 ) How to add a border (filled with 0's) around an existing array? 

In [19]:
arr1 = np.ones((5, 5))
arr1[:1, :] = 0
arr1[:, :1] = 0
arr1[4:, :] = 0
arr1[:, 4:] = 0
arr1

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 16) How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

***Example -***

`[[ 1 2 3 4 5 6 7]` `[ 8 9 10 11 12 13 14]]`

***Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20***

In [20]:
arr1 = np.arange(1, 15).reshape(2, 7)
arr1

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [21]:
# get 13
arr1[1, -2]

13

In [22]:
# get the first row only
arr1[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
# get the 3rd column only
arr1[:, 2]

array([ 3, 10])

In [24]:
# get [2, 4, 6],
arr1[0, 1::2]

array([2, 4, 6])

In [25]:
# replace 13 by 20
print(f"Before replacing :\n {arr1}")
arr1[1, -2] = 20
print(f"\nAfter replacing :\n {arr1}")

Before replacing :
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

After replacing :
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


#### 17) How to Convert a 1D array to a 2D array with 2 rows

In [26]:
arr1 = np.arange(0, 9)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
print(f"No of Dimension of the array : {arr1.ndim}")

No of Dimension of the array : 1


In [28]:
arr1 = arr1.reshape((3, 3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
print(f"No of Dimension of the array : {arr1.ndim}")

No of Dimension of the array : 2


#### 18) Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

***Input:***

a = `np.array([1,2,3])`

***Desired Output:***
   
   `array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`

In [30]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [31]:
a = np.append(np.repeat(a, 3), np.tile(a, 3))
print(a)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


#### 19) Write a program to show how Numpy taking less memory compared to Python List?

In [32]:
import sys

list1 = range(1000)
print("Size of each element of list in bytes: ", sys.getsizeof(list1))
print("Size of the whole list in bytes: ", sys.getsizeof(list1) * len(list1))

# declaring a Numpy array of 1000 elements
array = np.arange(1000)
print("\nSize of each element of the Numpy array in bytes: ", array.itemsize)
print("Size of the whole Numpy array in bytes: ", array.size * array.itemsize)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000

Size of each element of the Numpy array in bytes:  4
Size of the whole Numpy array in bytes:  4000


#### 20) Write a program to show how Numpy taking less time compared to Python List?

In [33]:
import time

size = 1000000
list1 = range(size)
list2 = range(size)
array1 = np.arange(size)
array2 = np.arange(size)

# list
initialTime = time.time()
resultantList = [(a * b) for a, b in zip(list1, list2)]
print(f"Time taken by Lists to perform multiplication: {(time.time() - initialTime)} s")

# numpy array
initialTime = time.time()
resultantArray = array1 * array2
print(
    f"\nTime taken by NumPy Arrays to perform multiplication: {(time.time() - initialTime)} s"
)

Time taken by Lists to perform multiplication: 0.5840020179748535 s

Time taken by NumPy Arrays to perform multiplication: 0.0050013065338134766 s
